name: widgetbook_golden_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  alchemist: ^0.11.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  pedantic_mono: ^1.28.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  widgetbook_workspace:
    path: widgetbook

flutter:
  uses-material-design: true
