name: widgetbook_golden_test
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.5.3
description: A new Flutter project.

dependencies:
  alchemist: ^0.11.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^3.0.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  intl: ^0.19.0
  pedantic_mono: ^1.28.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.3.3
  widgetbook: ^3.13.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  import_sorter: ^4.6.0
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.6.5
  widgetbook4_workspace:
    path: widgetbook4

flutter:
  uses-material-design: true
