name: widgetbook4_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  pedantic_mono: ^1.28.0
  widgetbook: ^3.13.1
  widgetbook_golden_test:
    path: ../

dev_dependencies:
  alchemist: ^0.11.0
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  widgetbook_generator: ^3.12.0

flutter:
  uses-material-design: true
